const constants = {
  kAppName: "Pious Store",
  kAppTagline: "Your own mega store",
  kApiBaseUrl: "http://localhost:8000/api/", //"http://192.168.29.65:8000/api/", // "http://localhost:8000/api/",
  kApiLogin: "auth/login/",
  kApiSignup: "auth/signup/",
  kApiLogout: "auth/logout/",
  kApiUsers: "users/",
  kApiProducts: "products/",
  kApiPayments: "payments/",
  kApiWishlists: "wishlists/",
  kApiCategories: "categories/",
  kApiProductsBuyer: "products-buyer/",
  kApiProductsSeller: "product-seller/",
  kApiProductsCategory: "product-category/",
  kApiProductsCartExtended: "product-cart/",
  kApiProductsCart: "generic/product-cart/",
  kApiProductsWishlistExtended: "product-wishlist/",
  kApiProductsWishlist: "generic/product-wishlist/",
  kApiUserWishlist: "user-wishlist/",
  kHomePage: "/",
  kLoginPage: "login/",
  kSignupPage: "signup/",
  kAboutPage: "about/",
  kShopPage: "shop/",
  kProfilePage: "profile/",
  kContactPage: "contact/",
  kCartPage: "cart/",
  kWishlistPage: "wishlist/",
  kAddProductPage: "add-product/",
};

export default constants;
