const constants = {
  kAppName: "Pious Store",
  kAppTagline: "Your own mega store",
  kApiBaseUrl: "http://localhost:8000/api/",
  kApiLogin: "auth/login/",
  kApiSignup: "auth/signup/",
  kApiLogout: "auth/logout/",
  kApiUsers: "users/",
  kApiProducts: "products/",
  kApiPayments: "payments/",
  kApiWishlists: "wishlists/",
  kApiCategories: "categories/",
  kApiProductsBuyer: "products-buyer/",
  kApiProductsSeller: "product-seller/",
  kApiProductsCategory: "product-category/",
  kApiProductsCart: "product-cart/",
  kApiUserWishlist: "user-wishlist/",
  kHomePage: "/",
  kLoginPage: "login/",
  kSignupPage: "signup/",
  kAboutPage: "about/",
  kShopPage: "shop/",
  kProfilePage: "profile/",
  kContactPage: "contact/",
  kCartPage: "cart/",
  kWishlistPage: "wishlist/",
};

export default constants;
